# config/symbols.yaml
# 中证A50指数成分股（官方50只，2024年12月调整）

csi_a50:
- symbol: 000063.SZ
  name: 中兴通讯
  industry: 通信设备
  list_date: '1997-11-18'
  weight: 1.481
  area: 广东
  market: 主板
  fullname: 中兴通讯股份有限公司
- symbol: 000333.SZ
  name: 美的集团
  industry: 家电
  list_date: '2013-09-18'
  weight: 4.289
  area: 广东
  market: 主板
  fullname: 美的集团股份有限公司
- symbol: 000617.SZ
  name: 中油资本
  industry: null
  list_date: null
  weight: 0.253
  area: null
  market: 主板
  fullname: null
- symbol: 000725.SZ
  name: 京东方A
  industry: 电子元件
  list_date: '2001-01-12'
  weight: 1.548
  area: 北京
  market: 主板
  fullname: 京东方科技集团股份有限公司
- symbol: 000792.SZ
  name: 盐湖股份
  industry: 化工
  list_date: '1997-09-04'
  weight: 1.07
  area: 青海
  market: 主板
  fullname: 青海盐湖工业股份有限公司
- symbol: 000938.SZ
  name: 紫光股份
  industry: IT服务
  list_date: '1999-11-04'
  weight: 0.545
  area: 北京
  market: 主板
  fullname: 紫光股份有限公司
- symbol: 002027.SZ
  name: 分众传媒
  industry: null
  list_date: null
  weight: 0.811
  area: null
  market: 主板
  fullname: null
- symbol: 002230.SZ
  name: 科大讯飞
  industry: 软件
  list_date: '2008-05-12'
  weight: 1.25
  area: 安徽
  market: 主板
  fullname: 科大讯飞股份有限公司
- symbol: 002371.SZ
  name: 北方华创
  industry: null
  list_date: null
  weight: 2.022
  area: null
  market: 主板
  fullname: null
- symbol: 002475.SZ
  name: 立讯精密
  industry: 消费电子
  list_date: '2010-09-15'
  weight: 3.201
  area: 广东
  market: 主板
  fullname: 立讯精密工业股份有限公司
- symbol: 002594.SZ
  name: 比亚迪
  industry: 汽车
  list_date: '2011-06-30'
  weight: 2.823
  area: 广东
  market: 主板
  fullname: 比亚迪股份有限公司
- symbol: 002714.SZ
  name: 牧原股份
  industry: null
  list_date: null
  weight: 1.514
  area: null
  market: 主板
  fullname: null
- symbol: 300015.SZ
  name: 爱尔眼科
  industry: 医疗服务
  list_date: '2009-10-30'
  weight: 0.586
  area: 湖南
  market: 创业板
  fullname: 爱尔眼科医院集团股份有限公司
- symbol: 300124.SZ
  name: 汇川技术
  industry: 自动化设备
  list_date: '2010-09-28'
  weight: 1.456
  area: 广东
  market: 创业板
  fullname: 深圳市汇川技术股份有限公司
- symbol: 300408.SZ
  name: 三环集团
  industry: null
  list_date: null
  weight: 0.645
  area: null
  market: 创业板
  fullname: null
- symbol: 300750.SZ
  name: 宁德时代
  industry: 电池
  list_date: '2018-06-11'
  weight: 10.767
  area: 福建
  market: 创业板
  fullname: 宁德时代新能源科技股份有限公司
- symbol: 300760.SZ
  name: 迈瑞医疗
  industry: 医疗器械
  list_date: '2018-10-16'
  weight: 1.35
  area: 广东
  market: 创业板
  fullname: 深圳迈瑞生物医疗电子股份有限公司
- symbol: 600009.SH
  name: 上海机场
  industry: null
  list_date: null
  weight: 0.43
  area: null
  market: 主板
  fullname: null
- symbol: 600019.SH
  name: 宝钢股份
  industry: 钢铁
  list_date: '2000-12-12'
  weight: 0.694
  area: 上海
  market: 主板
  fullname: 宝山钢铁股份有限公司
- symbol: 600028.SH
  name: 中国石化
  industry: 石油石化
  list_date: '2001-08-08'
  weight: 0.921
  area: 北京
  market: 主板
  fullname: 中国石油化工股份有限公司
- symbol: 600030.SH
  name: 中信证券
  industry: 证券
  list_date: '2003-01-06'
  weight: 2.941
  area: 广东
  market: 主板
  fullname: 中信证券股份有限公司
- symbol: 600031.SH
  name: 三一重工
  industry: 工程机械
  list_date: '2003-07-03'
  weight: 1.316
  area: 北京
  market: 主板
  fullname: 三一重工股份有限公司
- symbol: 600036.SH
  name: 招商银行
  industry: 银行
  list_date: '2002-04-09'
  weight: 5.805
  area: 广东
  market: 主板
  fullname: 招商银行股份有限公司
- symbol: 600048.SH
  name: 保利发展
  industry: null
  list_date: null
  weight: 0.53
  area: null
  market: 主板
  fullname: null
- symbol: 600111.SH
  name: 北方稀土
  industry: null
  list_date: null
  weight: 1.243
  area: null
  market: 主板
  fullname: null
- symbol: 600276.SH
  name: 恒瑞医药
  industry: 化学制药
  list_date: '2000-10-18'
  weight: 3.027
  area: 江苏
  market: 主板
  fullname: 江苏恒瑞医药股份有限公司
- symbol: 600309.SH
  name: 万华化学
  industry: 化工
  list_date: '2001-01-05'
  weight: 1.381
  area: 山东
  market: 主板
  fullname: 万华化学集团股份有限公司
- symbol: 600406.SH
  name: 国电南瑞
  industry: 电力设备
  list_date: '2003-10-16'
  weight: 0.972
  area: 江苏
  market: 主板
  fullname: 国电南瑞科技股份有限公司
- symbol: 600415.SH
  name: 小商品城
  industry: null
  list_date: null
  weight: 0.493
  area: null
  market: 主板
  fullname: null
- symbol: 600426.SH
  name: 华鲁恒升
  industry: null
  list_date: null
  weight: 0.459
  area: null
  market: 主板
  fullname: null
- symbol: 600436.SH
  name: 片仔癀
  industry: 中药
  list_date: '2003-06-16'
  weight: 0.566
  area: 福建
  market: 主板
  fullname: 漳州片仔癀药业股份有限公司
- symbol: 600519.SH
  name: 贵州茅台
  industry: 白酒
  list_date: '2001-08-27'
  weight: 8.629
  area: 贵州
  market: 主板
  fullname: 贵州茅台酒股份有限公司
- symbol: 600585.SH
  name: 海螺水泥
  industry: null
  list_date: null
  weight: 0.599
  area: null
  market: 主板
  fullname: null
- symbol: 600660.SH
  name: 福耀玻璃
  industry: null
  list_date: null
  weight: 1.153
  area: null
  market: 主板
  fullname: null
- symbol: 600887.SH
  name: 伊利股份
  industry: 食品饮料
  list_date: '1996-03-12'
  weight: 2.029
  area: 内蒙古
  market: 主板
  fullname: 内蒙古伊利实业集团股份有限公司
- symbol: 600893.SH
  name: 航发动力
  industry: null
  list_date: null
  weight: 0.541
  area: null
  market: 主板
  fullname: null
- symbol: 600900.SH
  name: 长江电力
  industry: 电力
  list_date: '2003-11-18'
  weight: 3.738
  area: 北京
  market: 主板
  fullname: 中国长江电力股份有限公司
- symbol: 600941.SH
  name: 中国移动
  industry: null
  list_date: null
  weight: 1.062
  area: null
  market: 主板
  fullname: null
- symbol: 601012.SH
  name: 隆基绿能
  industry: 光伏
  list_date: '2012-04-11'
  weight: 1.229
  area: 陕西
  market: 主板
  fullname: 隆基绿能科技股份有限公司
- symbol: 601088.SH
  name: 中国神华
  industry: null
  list_date: null
  weight: 1.482
  area: null
  market: 主板
  fullname: null
- symbol: 601318.SH
  name: 中国平安
  industry: 保险
  list_date: '2007-03-01'
  weight: 6.933
  area: 广东
  market: 主板
  fullname: 中国平安保险(集团)股份有限公司
- symbol: 601600.SH
  name: 中国铝业
  industry: 有色金属
  list_date: '2007-04-30'
  weight: 0.91
  area: 北京
  market: 主板
  fullname: 中国铝业股份有限公司
- symbol: 601668.SH
  name: 中国建筑
  industry: 工程建设
  list_date: '2009-07-29'
  weight: 1.173
  area: 北京
  market: 主板
  fullname: 中国建筑股份有限公司
- symbol: 601766.SH
  name: 中国中车
  industry: null
  list_date: null
  weight: 0.966
  area: null
  market: 主板
  fullname: null
- symbol: 601816.SH
  name: 京沪高铁
  industry: 铁路运输
  list_date: '2020-01-16'
  weight: 1.632
  area: 北京
  market: 主板
  fullname: 京沪高速铁路股份有限公司
- symbol: 601888.SH
  name: 中国中免
  industry: 旅游零售
  list_date: '2009-10-15'
  weight: 0.842
  area: 北京
  market: 主板
  fullname: 中国旅游集团中免股份有限公司
- symbol: 601899.SH
  name: 紫金矿业
  industry: 有色金属
  list_date: '2008-04-25'
  weight: 5.14
  area: 福建
  market: 主板
  fullname: 紫金矿业集团股份有限公司
- symbol: 603259.SH
  name: 药明康德
  industry: 医疗服务
  list_date: '2018-05-08'
  weight: 2.49
  area: 江苏
  market: 主板
  fullname: 无锡药明康德新药开发股份有限公司
- symbol: 605499.SH
  name: 东鹏饮料
  industry: null
  list_date: null
  weight: 0.599
  area: null
  market: 主板
  fullname: null
- symbol: 688981.SH
  name: 中芯国际
  industry: 半导体
  list_date: '2020-07-16'
  weight: 2.467
  area: 上海
  market: 科创板
  fullname: 中芯国际集成电路制造有限公司
csi_300: []
csi_500: []
